# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74add273e43ecf0fc808ca1b6f26961f3dca313c67c7d2643767b0af8bd9a484176e9ba858405e658b4a914ed0dcd89198db21206bb3af74ae8f4d49994d481

test:
  secret_key_base: c7a025fca97d5044574148a8207f91b428f3913555684678ddfcab7a84f37497bdbd61fe77ee9ef4b0d011d1c6f9dc8acaf6aab07e7566aef830847260c1c263

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
